import type { Bilingual } from "@/config/aram";

export const strings = {
  // Brand & global
  "brand.tagline": { en: "Citizen-first Digital Governance", ta: "குடிமகன் முதன்மை டிஜிட்டல் ஆளுகை" },
  "brand.meaning": { en: "Accessible • Responsive • Accountable • Modern", ta: "அணுகக்கூடிய • பதிலளிக்கும் • பொறுப்பான • நவீன" },
  "common.language": { en: "Language", ta: "மொழி" },
  "common.loading": { en: "Loading ARAM…", ta: "ARAM ஏற்றப்படுகிறது…" },
  "common.submit": { en: "Submit", ta: "சமர்ப்பிக்கவும்" },
  "common.next": { en: "Next", ta: "அடுத்து" },
  "common.back": { en: "Back", ta: "பின்செல்" },
  "common.cancel": { en: "Cancel", ta: "ரத்து" },
  "common.confirm": { en: "Confirm", ta: "உறுதிப்படுத்து" },
  "common.search": { en: "Search", ta: "தேடு" },
  "common.all": { en: "All", ta: "அனைத்தும்" },
  "common.status": { en: "Status", ta: "நிலை" },
  "common.category": { en: "Category", ta: "வகை" },
  "common.ward": { en: "Ward", ta: "வார்டு" },
  "common.department": { en: "Department", ta: "துறை" },
  "common.date": { en: "Date", ta: "தேதி" },
  "common.time": { en: "Time", ta: "நேரம்" },
  "common.location": { en: "Location", ta: "இடம்" },
  "common.viewAll": { en: "View all", ta: "அனைத்தையும் பார்" },
  "common.readMore": { en: "Read more", ta: "மேலும் படிக்க" },
  "common.optional": { en: "Optional", ta: "விருப்பத்தேர்வு" },
  "common.required": { en: "Required", ta: "அவசியம்" },
  "common.demoData": { en: "Demo data", ta: "மாதிரி தரவு" },
  "common.close": { en: "Close", ta: "மூடு" },
  "common.download": { en: "Download receipt", ta: "ரசீதை பதிவிறக்கு" },
  "common.notFound": { en: "Nothing found", ta: "எதுவும் கிடைக்கவில்லை" },

  // Navigation
  "nav.home": { en: "Home", ta: "முகப்பு" },
  "nav.report": { en: "Report an Issue", ta: "பிரச்சினையை பதிவு செய்" },
  "nav.track": { en: "Track My Issue", ta: "எனது புகாரை கண்காணி" },
  "nav.map": { en: "Live Map", ta: "நேரடி வரைபடம்" },
  "nav.schemes": { en: "Government Schemes", ta: "அரசு திட்டங்கள்" },
  "nav.appointment": { en: "Meet Your MLA", ta: "எம்.எல்.ஏ.வை சந்திக்க" },
  "nav.projects": { en: "Development", ta: "மேம்பாட்டு பணிகள்" },
  "nav.wards": { en: "Your Ward", ta: "உங்கள் வார்டு" },
  "nav.updates": { en: "Updates", ta: "செய்திகள்" },
  "nav.transparency": { en: "Transparency", ta: "வெளிப்படைத்தன்மை" },
  "nav.notifications": { en: "Notifications", ta: "அறிவிப்புகள்" },
  "nav.login": { en: "Login", ta: "உள்நுழை" },
  "nav.logout": { en: "Logout", ta: "வெளியேறு" },
  "nav.dashboard": { en: "My Dashboard", ta: "எனது டாஷ்போர்டு" },
  "nav.menu": { en: "Menu", ta: "பட்டி" },
  "nav.emergency": { en: "Emergency Help", ta: "அவசர உதவி" },

  // Home
  "home.hero.title": { en: "Your Voice. Your Area. Your ARAM.", ta: "உங்கள் குரல். உங்கள் பகுதி. உங்கள் ARAM." },
  "home.hero.sub": {
    en: "Report issues, access services, track progress and stay connected with your constituency.",
    ta: "பிரச்சினைகளை பதிவு செய்யுங்கள், சேவைகளை அணுகுங்கள், முன்னேற்றத்தை கண்காணியுங்கள், உங்கள் தொகுதியுடன் இணைந்திருங்கள்.",
  },
  "home.search.placeholder": { en: "What do you need help with?", ta: "உங்களுக்கு என்ன உதவி வேண்டும்?" },
  "home.search.s1": { en: "Report a road problem", ta: "சாலை பிரச்சினையை பதிவு செய்ய" },
  "home.search.s2": { en: "Check my complaint", ta: "எனது புகாரை பார்க்க" },
  "home.search.s3": { en: "Find a government scheme", ta: "அரசு திட்டத்தை கண்டறிய" },
  "home.search.s4": { en: "Book an appointment", ta: "சந்திப்பு பதிவு செய்ய" },
  "home.search.s5": { en: "Find an emergency service", ta: "அவசர சேவையை கண்டறிய" },
  "home.search.s6": { en: "View constituency projects", ta: "தொகுதி திட்டங்களை பார்க்க" },
  "home.services.title": { en: "Quick Citizen Services", ta: "விரைவு குடிமகன் சேவைகள்" },
  "home.live.title": { en: "ARAM Live Status", ta: "ARAM நேரடி நிலை" },
  "home.live.resolved": { en: "Complaints Resolved", ta: "தீர்க்கப்பட்ட புகார்கள்" },
  "home.live.progress": { en: "Complaints In Progress", ta: "நடைபெறும் புகார்கள்" },
  "home.live.new": { en: "New Complaints", ta: "புதிய புகார்கள்" },
  "home.live.cta": { en: "View Constituency Status", ta: "தொகுதி நிலையை பார்க்க" },
  "home.map.title": { en: "What's Happening Around You?", ta: "உங்கள் சுற்றுவட்டாரத்தில் என்ன நடக்கிறது?" },
  "home.map.sub": { en: "Live civic issues and development works across the constituency.", ta: "தொகுதி முழுவதும் நேரடி குடிமை பிரச்சினைகள் மற்றும் மேம்பாட்டு பணிகள்." },
  "home.updates.title": { en: "Latest Constituency Updates", ta: "சமீபத்திய தொகுதி செய்திகள்" },
  "home.schemes.title": { en: "Schemes you may be eligible for", ta: "உங்களுக்கு பொருந்தக்கூடிய திட்டங்கள்" },

  // Complaint flow
  "report.title": { en: "Report an Issue", ta: "பிரச்சினையை பதிவு செய்" },
  "report.step1": { en: "Choose category", ta: "வகையை தேர்வு செய்" },
  "report.step2": { en: "Describe the problem", ta: "பிரச்சினையை விவரிக்கவும்" },
  "report.step3": { en: "Add evidence", ta: "ஆதாரம் சேர்க்கவும்" },
  "report.step4": { en: "Select location", ta: "இடத்தை தேர்வு செய்" },
  "report.step5": { en: "AI review", ta: "AI சரிபார்ப்பு" },
  "report.step6": { en: "Submit", ta: "சமர்ப்பிக்கவும்" },
  "report.describe.placeholder": { en: "Tell us what is wrong, in your own words…", ta: "என்ன பிரச்சினை என்பதை உங்கள் சொற்களில் கூறுங்கள்…" },
  "report.voice": { en: "Speak instead of typing", ta: "தட்டச்சு செய்யாமல் பேசுங்கள்" },
  "report.listening": { en: "Listening… speak now", ta: "கேட்கிறது… இப்போது பேசுங்கள்" },
  "report.voiceUnsupported": { en: "Voice input is not supported on this device.", ta: "இந்த சாதனத்தில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை." },
  "report.upload.photo": { en: "Photo", ta: "புகைப்படம்" },
  "report.upload.video": { en: "Video", ta: "வீடியோ" },
  "report.upload.voice": { en: "Voice note", ta: "குரல் குறிப்பு" },
  "report.loc.current": { en: "Use Current Location", ta: "தற்போதைய இடத்தை பயன்படுத்து" },
  "report.loc.search": { en: "Search Address", ta: "முகவரியை தேடு" },
  "report.loc.map": { en: "Select on Map", ta: "வரைபடத்தில் தேர்வு செய்" },
  "report.ai.detected": { en: "Detected Category", ta: "கண்டறியப்பட்ட வகை" },
  "report.ai.dept": { en: "Suggested Department", ta: "பரிந்துரைக்கப்பட்ட துறை" },
  "report.ai.priority": { en: "Priority", ta: "முன்னுரிமை" },
  "report.ai.duplicate": { en: "Possible Duplicate", ta: "சாத்தியமான நகல்" },
  "report.ai.confirm": { en: "I confirm these details are correct", ta: "இந்த விவரங்கள் சரியானவை என உறுதிப்படுத்துகிறேன்" },
  "report.success": { en: "Complaint registered", ta: "புகார் பதிவு செய்யப்பட்டது" },
  "report.receipt": { en: "Digital Receipt", ta: "டிஜிட்டல் ரசீது" },
  "report.trackNow": { en: "Track Status", ta: "நிலையை கண்காணி" },
  "report.err.category": { en: "Please choose a category.", ta: "தயவுசெய்து ஒரு வகையை தேர்வு செய்யவும்." },
  "report.err.description": { en: "Please describe the problem in at least 10 characters.", ta: "குறைந்தது 10 எழுத்துகளில் பிரச்சினையை விவரிக்கவும்." },
  "report.err.location": { en: "Please select a location.", ta: "தயவுசெய்து இடத்தை தேர்வு செய்யவும்." },
  "report.err.confirm": { en: "Please confirm the details before submitting.", ta: "சமர்ப்பிக்கும் முன் விவரங்களை உறுதிப்படுத்தவும்." },

  // Tracking
  "track.title": { en: "Track My Issue", ta: "எனது புகாரை கண்காணி" },
  "track.placeholder": { en: "Enter ARAM Complaint ID, e.g. ARAM-2026-000245", ta: "ARAM புகார் எண்ணை உள்ளிடவும், எ.கா. ARAM-2026-000245" },
  "track.timeline": { en: "Progress Timeline", ta: "முன்னேற்ற காலவரிசை" },
  "track.beforeAfter": { en: "Before & After Proof", ta: "முன் & பின் ஆதாரம்" },
  "track.before": { en: "Before", ta: "முன்" },
  "track.after": { en: "After", ta: "பின்" },
  "track.slider": { en: "Slider", ta: "ஸ்லைடர்" },
  "track.sideBySide": { en: "Side by side", ta: "அருகருகே" },
  "track.completedOn": { en: "Work Completed On", ta: "பணி முடிந்த நாள்" },
  "track.verify.q": { en: "Has your issue been resolved?", ta: "உங்கள் பிரச்சினை தீர்க்கப்பட்டதா?" },
  "track.verify.yes": { en: "Yes, Resolved", ta: "ஆம், தீர்ந்தது" },
  "track.verify.no": { en: "No, Still an Issue", ta: "இல்லை, இன்னும் உள்ளது" },
  "track.verify.rating": { en: "Rate the service", ta: "சேவையை மதிப்பிடுங்கள்" },
  "track.verify.comment": { en: "Add a comment", ta: "கருத்து சேர்க்கவும்" },
  "track.verify.reopen": { en: "Reopen Complaint", ta: "புகாரை மீண்டும் திற" },
  "track.verify.thanks": { en: "Thank you for verifying.", ta: "உறுதிப்படுத்தியதற்கு நன்றி." },

  // Schemes
  "schemes.title": { en: "Find Government Schemes", ta: "அரசு திட்டங்களை கண்டறியுங்கள்" },
  "schemes.finder": { en: "Find Schemes for Me", ta: "எனக்கான திட்டங்களை கண்டறி" },
  "schemes.overview": { en: "Overview", ta: "மேலோட்டம்" },
  "schemes.benefits": { en: "Benefits", ta: "பயன்கள்" },
  "schemes.eligibility": { en: "Eligibility", ta: "தகுதி" },
  "schemes.documents": { en: "Required Documents", ta: "தேவையான ஆவணங்கள்" },
  "schemes.process": { en: "Application Process", ta: "விண்ணப்ப நடைமுறை" },
  "schemes.source": { en: "Official Source", ta: "அதிகாரப்பூர்வ ஆதாரம்" },
  "schemes.apply": { en: "Apply", ta: "விண்ணப்பிக்க" },
  "schemes.relevant": { en: "Potentially Relevant Schemes", ta: "பொருந்தக்கூடிய திட்டங்கள்" },
  "schemes.disclaimer": {
    en: "This is guidance only. Final eligibility is decided by the concerned department against official rules.",
    ta: "இது வழிகாட்டுதல் மட்டுமே. இறுதி தகுதி சம்பந்தப்பட்ட துறையால் அதிகாரப்பூர்வ விதிகளின்படி முடிவு செய்யப்படும்.",
  },
  "schemes.q.age": { en: "Your age", ta: "உங்கள் வயது" },
  "schemes.q.gender": { en: "Gender", ta: "பாலினம்" },
  "schemes.q.income": { en: "Annual family income (₹)", ta: "ஆண்டு குடும்ப வருமானம் (₹)" },
  "schemes.q.occupation": { en: "Occupation", ta: "தொழில்" },
  "schemes.q.education": { en: "Education", ta: "கல்வி" },

  // Appointment
  "appt.title": { en: "Meet Your MLA", ta: "உங்கள் எம்.எல்.ஏ.வை சந்திக்க" },
  "appt.request": { en: "Request Appointment", ta: "சந்திப்பு கோரிக்கை" },
  "appt.purpose": { en: "Purpose", ta: "நோக்கம்" },
  "appt.prefDate": { en: "Preferred Date", ta: "விரும்பிய தேதி" },
  "appt.prefTime": { en: "Available Time", ta: "கிடைக்கும் நேரம்" },
  "appt.description": { en: "Description", ta: "விவரம்" },
  "appt.docs": { en: "Supporting Documents", ta: "ஆதரவு ஆவணங்கள்" },
  "appt.success": { en: "Appointment request submitted", ta: "சந்திப்பு கோரிக்கை சமர்ப்பிக்கப்பட்டது" },
  "appt.officeHours": { en: "Office Hours", ta: "அலுவலக நேரம்" },

  // Projects / wards / transparency
  "projects.title": { en: "See Where Development Is Happening", ta: "மேம்பாடு எங்கே நடக்கிறது என்பதை பாருங்கள்" },
  "projects.progress": { en: "Progress", ta: "முன்னேற்றம்" },
  "projects.budget": { en: "Approved Budget", ta: "அங்கீகரிக்கப்பட்ட நிதி" },
  "projects.start": { en: "Start Date", ta: "தொடக்க தேதி" },
  "projects.end": { en: "Expected Completion", ta: "எதிர்பார்க்கப்படும் நிறைவு" },
  "wards.title": { en: "Explore Your Ward", ta: "உங்கள் வார்டை அறியுங்கள்" },
  "wards.overview": { en: "Ward Overview", ta: "வார்டு மேலோட்டம்" },
  "wards.facilities": { en: "Important Facilities", ta: "முக்கிய வசதிகள்" },
  "transparency.title": { en: "Constituency at a Glance", ta: "ஒரே பார்வையில் தொகுதி" },
  "transparency.total": { en: "Total Complaints", ta: "மொத்த புகார்கள்" },
  "transparency.avgTime": { en: "Average Resolution Time", ta: "சராசரி தீர்வு நேரம்" },
  "transparency.satisfaction": { en: "Citizen Satisfaction", ta: "குடிமக்கள் திருப்தி" },
  "transparency.projects": { en: "Development Projects", ta: "மேம்பாட்டு திட்டங்கள்" },
  "transparency.completed": { en: "Completed Projects", ta: "முடிந்த திட்டங்கள்" },
  "transparency.days": { en: "days", ta: "நாட்கள்" },

  // Updates
  "updates.title": { en: "Latest Constituency Updates", ta: "சமீபத்திய தொகுதி செய்திகள்" },

  // Notifications
  "notif.title": { en: "Notification Centre", ta: "அறிவிப்பு மையம்" },
  "notif.unread": { en: "Unread", ta: "படிக்காதவை" },
  "notif.read": { en: "Read", ta: "படித்தவை" },
  "notif.priority": { en: "Priority", ta: "முன்னுரிமை" },
  "notif.markAll": { en: "Mark all as read", ta: "அனைத்தையும் படித்ததாக குறி" },
  "notif.empty": { en: "No notifications yet.", ta: "இதுவரை அறிவிப்புகள் இல்லை." },

  // Auth
  "auth.title": { en: "Login to ARAM", ta: "ARAM இல் உள்நுழையவும்" },
  "auth.sub": { en: "One secure entry point for citizens and officials.", ta: "குடிமக்கள் மற்றும் அலுவலர்களுக்கான ஒரே பாதுகாப்பான நுழைவு." },
  "auth.mobile": { en: "Mobile number", ta: "கைபேசி எண்" },
  "auth.otp": { en: "One-time password", ta: "ஒரு முறை கடவுச்சொல்" },
  "auth.sendOtp": { en: "Send OTP", ta: "OTP அனுப்பு" },
  "auth.verify": { en: "Verify & Continue", ta: "சரிபார்த்து தொடரவும்" },
  "auth.demoNote": { en: "Demo login — choose a role to preview its workspace. Any 6-digit code works.", ta: "மாதிரி உள்நுழைவு — பணியிடத்தை பார்க்க ஒரு பங்கை தேர்வு செய்யவும். எந்த 6 இலக்க குறியீடும் வேலை செய்யும்." },
  "auth.role": { en: "Continue as", ta: "இவ்வாறு தொடரவும்" },
  "auth.err.mobile": { en: "Enter a valid 10-digit mobile number.", ta: "சரியான 10 இலக்க கைபேசி எண்ணை உள்ளிடவும்." },
  "auth.err.otp": { en: "Enter the 6-digit code.", ta: "6 இலக்க குறியீட்டை உள்ளிடவும்." },

  // Dashboard
  "dash.greeting": { en: "Welcome back", ta: "மீண்டும் வருக" },
  "dash.myComplaints": { en: "My Complaints", ta: "எனது புகார்கள்" },
  "dash.myAppointments": { en: "My Appointments", ta: "எனது சந்திப்புகள்" },
  "dash.actionNeeded": { en: "Action needed from you", ta: "உங்களிடமிருந்து நடவடிக்கை தேவை" },

  // Console
  "console.title": { en: "ARAM Console", ta: "ARAM கன்சோல்" },
  "console.super": { en: "Super Admin", ta: "முதன்மை நிர்வாகி" },
  "console.constituency": { en: "Constituency Admin", ta: "தொகுதி நிர்வாகி" },
  "console.department": { en: "Department Admin", ta: "துறை நிர்வாகி" },
  "console.officer": { en: "Field Officer", ta: "கள அலுவலர்" },
  "console.content": { en: "Content Admin", ta: "உள்ளடக்க நிர்வாகி" },
  "console.today": { en: "Today's Assignments", ta: "இன்றைய பணிகள்" },
  "console.navigate": { en: "Navigate", ta: "வழிகாட்டு" },
  "console.workUpdate": { en: "Work Update", ta: "பணி புதுப்பிப்பு" },
  "console.completeWork": { en: "Complete Work", ta: "பணியை முடி" },
  "console.restricted": { en: "This workspace requires the matching role.", ta: "இந்த பணியிடத்திற்கு பொருந்தும் பங்கு தேவை." },

  // AI assistant
  "ai.title": { en: "ARAM Assistant", ta: "ARAM உதவியாளர்" },
  "ai.sub": { en: "Ask about complaints, schemes, documents or appointments.", ta: "புகார்கள், திட்டங்கள், ஆவணங்கள் அல்லது சந்திப்புகள் குறித்து கேளுங்கள்." },
  "ai.placeholder": { en: "Type your question…", ta: "உங்கள் கேள்வியை தட்டச்சு செய்யுங்கள்…" },
  "ai.p1": { en: "How do I report a road problem?", ta: "சாலை பிரச்சினையை எப்படி பதிவு செய்வது?" },
  "ai.p2": { en: "Which documents are required for this scheme?", ta: "இந்த திட்டத்திற்கு என்ன ஆவணங்கள் தேவை?" },
  "ai.p3": { en: "Where is my complaint?", ta: "எனது புகார் எங்கே உள்ளது?" },
  "ai.p4": { en: "How do I meet the MLA?", ta: "எம்.எல்.ஏ.வை எப்படி சந்திப்பது?" },
  "ai.demo": { en: "Demo assistant — responses are simulated.", ta: "மாதிரி உதவியாளர் — பதில்கள் உருவகப்படுத்தப்பட்டவை." },

  // Accessibility
  "a11y.title": { en: "Accessibility", ta: "அணுகல்தன்மை" },
  "a11y.largeText": { en: "Large text", ta: "பெரிய எழுத்து" },
  "a11y.contrast": { en: "High contrast", ta: "அதிக மாறுபாடு" },

  // Map
  "map.title": { en: "Live Constituency Map", ta: "நேரடி தொகுதி வரைபடம்" },
  "map.normal": { en: "Normal Map", ta: "சாதாரண வரைபடம்" },
  "map.heat": { en: "Heat Map", ta: "வெப்ப வரைபடம்" },
  "map.needsKey": {
    en: "Interactive Google Map needs a Maps JavaScript API key. Add VITE_GOOGLE_MAPS_API_KEY to enable it — the list below stays fully usable meanwhile.",
    ta: "ஊடாடும் Google வரைபடத்திற்கு Maps JavaScript API விசை தேவை. VITE_GOOGLE_MAPS_API_KEY சேர்க்கவும் — அதுவரை கீழே உள்ள பட்டியல் பயன்படுத்தக்கூடியது.",
  },
  "map.legend": { en: "Legend", ta: "விளக்கம்" },
} satisfies Record<string, Bilingual>;

export type StringKey = keyof typeof strings;