/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutAppointmentsRouteImport } from './routes/_layout.appointments'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutDevelopmentRouteImport } from './routes/_layout.development'
import { Route as LayoutLoginRouteImport } from './routes/_layout.login'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout.notifications'
import { Route as LayoutSchemesRouteImport } from './routes/_layout.schemes'
import { Route as LayoutTransparencyRouteImport } from './routes/_layout.transparency'
import { Route as ApiAppointmentsRouteImport } from './routes/api.appointments'
import { Route as ApiComplaintsRouteImport } from './routes/api.complaints'
import { Route as ApiDbTestRouteImport } from './routes/api.db-test'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiStatsRouteImport } from './routes/api.stats'
import { Route as LayoutComplaintsRegisterRouteImport } from './routes/_layout.complaints.register'
import { Route as LayoutComplaintsTrackRouteImport } from './routes/_layout.complaints.track'
import { Route as LayoutConsoleConstituencyRouteImport } from './routes/_layout.console.constituency'
import { Route as LayoutConsoleContentRouteImport } from './routes/_layout.console.content'
import { Route as LayoutConsoleDepartmentRouteImport } from './routes/_layout.console.department'
import { Route as LayoutConsoleOfficerRouteImport } from './routes/_layout.console.officer'
import { Route as LayoutConsoleSuperRouteImport } from './routes/_layout.console.super'
import { Route as LayoutDashboardCitizenRouteImport } from './routes/_layout.dashboard.citizen'
import { Route as LayoutDashboardConstituencyRouteImport } from './routes/_layout.dashboard.constituency'
import { Route as LayoutDashboardDepartmentRouteImport } from './routes/_layout.dashboard.department'
import { Route as LayoutDashboardOfficerRouteImport } from './routes/_layout.dashboard.officer'
import { Route as LayoutDashboardSuperadminRouteImport } from './routes/_layout.dashboard.superadmin'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiComplaintsIdRouteImport } from './routes/api.complaints.$id'
import { Route as ApiAuthCitizenOtpRequestRouteImport } from './routes/api.auth.citizen.otp.request'
import { Route as ApiAuthCitizenOtpVerifyRouteImport } from './routes/api.auth.citizen.otp.verify'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppointmentsRoute = LayoutAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevelopmentRoute = LayoutDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSchemesRoute = LayoutSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransparencyRoute = LayoutTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAppointmentsRoute = ApiAppointmentsRouteImport.update({
  id: '/api/appointments',
  path: '/api/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsRoute = ApiComplaintsRouteImport.update({
  id: '/api/complaints',
  path: '/api/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbTestRoute = ApiDbTestRouteImport.update({
  id: '/api/db-test',
  path: '/api/db-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutComplaintsRegisterRoute =
  LayoutComplaintsRegisterRouteImport.update({
    id: '/complaints/register',
    path: '/complaints/register',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutComplaintsTrackRoute = LayoutComplaintsTrackRouteImport.update({
  id: '/complaints/track',
  path: '/complaints/track',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsoleConstituencyRoute =
  LayoutConsoleConstituencyRouteImport.update({
    id: '/console/constituency',
    path: '/console/constituency',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutConsoleContentRoute = LayoutConsoleContentRouteImport.update({
  id: '/console/content',
  path: '/console/content',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsoleDepartmentRoute = LayoutConsoleDepartmentRouteImport.update({
  id: '/console/department',
  path: '/console/department',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsoleOfficerRoute = LayoutConsoleOfficerRouteImport.update({
  id: '/console/officer',
  path: '/console/officer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsoleSuperRoute = LayoutConsoleSuperRouteImport.update({
  id: '/console/super',
  path: '/console/super',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardCitizenRoute = LayoutDashboardCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardConstituencyRoute =
  LayoutDashboardConstituencyRouteImport.update({
    id: '/constituency',
    path: '/constituency',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardDepartmentRoute =
  LayoutDashboardDepartmentRouteImport.update({
    id: '/department',
    path: '/department',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardOfficerRoute = LayoutDashboardOfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardSuperadminRoute =
  LayoutDashboardSuperadminRouteImport.update({
    id: '/superadmin',
    path: '/superadmin',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsIdRoute = ApiComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiComplaintsRoute,
} as any)
const ApiAuthCitizenOtpRequestRoute =
  ApiAuthCitizenOtpRequestRouteImport.update({
    id: '/api/auth/citizen/otp/request',
    path: '/api/auth/citizen/otp/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCitizenOtpVerifyRoute = ApiAuthCitizenOtpVerifyRouteImport.update({
  id: '/api/auth/citizen/otp/verify',
  path: '/api/auth/citizen/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/appointments': typeof LayoutAppointmentsRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/development': typeof LayoutDevelopmentRoute
  '/login': typeof LayoutLoginRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/schemes': typeof LayoutSchemesRoute
  '/transparency': typeof LayoutTransparencyRoute
  '/api/appointments': typeof ApiAppointmentsRoute
  '/api/complaints': typeof ApiComplaintsRouteWithChildren
  '/api/db-test': typeof ApiDbTestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/stats': typeof ApiStatsRoute
  '/complaints/register': typeof LayoutComplaintsRegisterRoute
  '/complaints/track': typeof LayoutComplaintsTrackRoute
  '/console/constituency': typeof LayoutConsoleConstituencyRoute
  '/console/content': typeof LayoutConsoleContentRoute
  '/console/department': typeof LayoutConsoleDepartmentRoute
  '/console/officer': typeof LayoutConsoleOfficerRoute
  '/console/super': typeof LayoutConsoleSuperRoute
  '/dashboard/citizen': typeof LayoutDashboardCitizenRoute
  '/dashboard/constituency': typeof LayoutDashboardConstituencyRoute
  '/dashboard/department': typeof LayoutDashboardDepartmentRoute
  '/dashboard/officer': typeof LayoutDashboardOfficerRoute
  '/dashboard/superadmin': typeof LayoutDashboardSuperadminRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/complaints/$id': typeof ApiComplaintsIdRoute
  '/api/auth/citizen/otp/request': typeof ApiAuthCitizenOtpRequestRoute
  '/api/auth/citizen/otp/verify': typeof ApiAuthCitizenOtpVerifyRoute
}
export interface FileRoutesByTo {
  '/appointments': typeof LayoutAppointmentsRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/development': typeof LayoutDevelopmentRoute
  '/login': typeof LayoutLoginRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/schemes': typeof LayoutSchemesRoute
  '/transparency': typeof LayoutTransparencyRoute
  '/api/appointments': typeof ApiAppointmentsRoute
  '/api/complaints': typeof ApiComplaintsRouteWithChildren
  '/api/db-test': typeof ApiDbTestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/stats': typeof ApiStatsRoute
  '/': typeof LayoutIndexRoute
  '/complaints/register': typeof LayoutComplaintsRegisterRoute
  '/complaints/track': typeof LayoutComplaintsTrackRoute
  '/console/constituency': typeof LayoutConsoleConstituencyRoute
  '/console/content': typeof LayoutConsoleContentRoute
  '/console/department': typeof LayoutConsoleDepartmentRoute
  '/console/officer': typeof LayoutConsoleOfficerRoute
  '/console/super': typeof LayoutConsoleSuperRoute
  '/dashboard/citizen': typeof LayoutDashboardCitizenRoute
  '/dashboard/constituency': typeof LayoutDashboardConstituencyRoute
  '/dashboard/department': typeof LayoutDashboardDepartmentRoute
  '/dashboard/officer': typeof LayoutDashboardOfficerRoute
  '/dashboard/superadmin': typeof LayoutDashboardSuperadminRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/complaints/$id': typeof ApiComplaintsIdRoute
  '/api/auth/citizen/otp/request': typeof ApiAuthCitizenOtpRequestRoute
  '/api/auth/citizen/otp/verify': typeof ApiAuthCitizenOtpVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/appointments': typeof LayoutAppointmentsRoute
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/development': typeof LayoutDevelopmentRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/schemes': typeof LayoutSchemesRoute
  '/_layout/transparency': typeof LayoutTransparencyRoute
  '/api/appointments': typeof ApiAppointmentsRoute
  '/api/complaints': typeof ApiComplaintsRouteWithChildren
  '/api/db-test': typeof ApiDbTestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/stats': typeof ApiStatsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/complaints/register': typeof LayoutComplaintsRegisterRoute
  '/_layout/complaints/track': typeof LayoutComplaintsTrackRoute
  '/_layout/console/constituency': typeof LayoutConsoleConstituencyRoute
  '/_layout/console/content': typeof LayoutConsoleContentRoute
  '/_layout/console/department': typeof LayoutConsoleDepartmentRoute
  '/_layout/console/officer': typeof LayoutConsoleOfficerRoute
  '/_layout/console/super': typeof LayoutConsoleSuperRoute
  '/_layout/dashboard/citizen': typeof LayoutDashboardCitizenRoute
  '/_layout/dashboard/constituency': typeof LayoutDashboardConstituencyRoute
  '/_layout/dashboard/department': typeof LayoutDashboardDepartmentRoute
  '/_layout/dashboard/officer': typeof LayoutDashboardOfficerRoute
  '/_layout/dashboard/superadmin': typeof LayoutDashboardSuperadminRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/complaints/$id': typeof ApiComplaintsIdRoute
  '/api/auth/citizen/otp/request': typeof ApiAuthCitizenOtpRequestRoute
  '/api/auth/citizen/otp/verify': typeof ApiAuthCitizenOtpVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/dashboard'
    | '/development'
    | '/login'
    | '/notifications'
    | '/schemes'
    | '/transparency'
    | '/api/appointments'
    | '/api/complaints'
    | '/api/db-test'
    | '/api/notifications'
    | '/api/stats'
    | '/complaints/register'
    | '/complaints/track'
    | '/console/constituency'
    | '/console/content'
    | '/console/department'
    | '/console/officer'
    | '/console/super'
    | '/dashboard/citizen'
    | '/dashboard/constituency'
    | '/dashboard/department'
    | '/dashboard/officer'
    | '/dashboard/superadmin'
    | '/api/auth/login'
    | '/api/complaints/$id'
    | '/api/auth/citizen/otp/request'
    | '/api/auth/citizen/otp/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/appointments'
    | '/dashboard'
    | '/development'
    | '/login'
    | '/notifications'
    | '/schemes'
    | '/transparency'
    | '/api/appointments'
    | '/api/complaints'
    | '/api/db-test'
    | '/api/notifications'
    | '/api/stats'
    | '/'
    | '/complaints/register'
    | '/complaints/track'
    | '/console/constituency'
    | '/console/content'
    | '/console/department'
    | '/console/officer'
    | '/console/super'
    | '/dashboard/citizen'
    | '/dashboard/constituency'
    | '/dashboard/department'
    | '/dashboard/officer'
    | '/dashboard/superadmin'
    | '/api/auth/login'
    | '/api/complaints/$id'
    | '/api/auth/citizen/otp/request'
    | '/api/auth/citizen/otp/verify'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/appointments'
    | '/_layout/dashboard'
    | '/_layout/development'
    | '/_layout/login'
    | '/_layout/notifications'
    | '/_layout/schemes'
    | '/_layout/transparency'
    | '/api/appointments'
    | '/api/complaints'
    | '/api/db-test'
    | '/api/notifications'
    | '/api/stats'
    | '/_layout/'
    | '/_layout/complaints/register'
    | '/_layout/complaints/track'
    | '/_layout/console/constituency'
    | '/_layout/console/content'
    | '/_layout/console/department'
    | '/_layout/console/officer'
    | '/_layout/console/super'
    | '/_layout/dashboard/citizen'
    | '/_layout/dashboard/constituency'
    | '/_layout/dashboard/department'
    | '/_layout/dashboard/officer'
    | '/_layout/dashboard/superadmin'
    | '/api/auth/login'
    | '/api/complaints/$id'
    | '/api/auth/citizen/otp/request'
    | '/api/auth/citizen/otp/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiAppointmentsRoute: typeof ApiAppointmentsRoute
  ApiComplaintsRoute: typeof ApiComplaintsRouteWithChildren
  ApiDbTestRoute: typeof ApiDbTestRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthCitizenOtpRequestRoute: typeof ApiAuthCitizenOtpRequestRoute
  ApiAuthCitizenOtpVerifyRoute: typeof ApiAuthCitizenOtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/appointments': {
      id: '/_layout/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof LayoutAppointmentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/development': {
      id: '/_layout/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof LayoutDevelopmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/schemes': {
      id: '/_layout/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof LayoutSchemesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transparency': {
      id: '/_layout/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof LayoutTransparencyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/appointments': {
      id: '/api/appointments'
      path: '/api/appointments'
      fullPath: '/api/appointments'
      preLoaderRoute: typeof ApiAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints': {
      id: '/api/complaints'
      path: '/api/complaints'
      fullPath: '/api/complaints'
      preLoaderRoute: typeof ApiComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db-test': {
      id: '/api/db-test'
      path: '/api/db-test'
      fullPath: '/api/db-test'
      preLoaderRoute: typeof ApiDbTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/complaints/register': {
      id: '/_layout/complaints/register'
      path: '/complaints/register'
      fullPath: '/complaints/register'
      preLoaderRoute: typeof LayoutComplaintsRegisterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/complaints/track': {
      id: '/_layout/complaints/track'
      path: '/complaints/track'
      fullPath: '/complaints/track'
      preLoaderRoute: typeof LayoutComplaintsTrackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/console/constituency': {
      id: '/_layout/console/constituency'
      path: '/console/constituency'
      fullPath: '/console/constituency'
      preLoaderRoute: typeof LayoutConsoleConstituencyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/console/content': {
      id: '/_layout/console/content'
      path: '/console/content'
      fullPath: '/console/content'
      preLoaderRoute: typeof LayoutConsoleContentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/console/department': {
      id: '/_layout/console/department'
      path: '/console/department'
      fullPath: '/console/department'
      preLoaderRoute: typeof LayoutConsoleDepartmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/console/officer': {
      id: '/_layout/console/officer'
      path: '/console/officer'
      fullPath: '/console/officer'
      preLoaderRoute: typeof LayoutConsoleOfficerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/console/super': {
      id: '/_layout/console/super'
      path: '/console/super'
      fullPath: '/console/super'
      preLoaderRoute: typeof LayoutConsoleSuperRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/citizen': {
      id: '/_layout/dashboard/citizen'
      path: '/citizen'
      fullPath: '/dashboard/citizen'
      preLoaderRoute: typeof LayoutDashboardCitizenRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/constituency': {
      id: '/_layout/dashboard/constituency'
      path: '/constituency'
      fullPath: '/dashboard/constituency'
      preLoaderRoute: typeof LayoutDashboardConstituencyRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/department': {
      id: '/_layout/dashboard/department'
      path: '/department'
      fullPath: '/dashboard/department'
      preLoaderRoute: typeof LayoutDashboardDepartmentRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/officer': {
      id: '/_layout/dashboard/officer'
      path: '/officer'
      fullPath: '/dashboard/officer'
      preLoaderRoute: typeof LayoutDashboardOfficerRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/superadmin': {
      id: '/_layout/dashboard/superadmin'
      path: '/superadmin'
      fullPath: '/dashboard/superadmin'
      preLoaderRoute: typeof LayoutDashboardSuperadminRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/$id': {
      id: '/api/complaints/$id'
      path: '/$id'
      fullPath: '/api/complaints/$id'
      preLoaderRoute: typeof ApiComplaintsIdRouteImport
      parentRoute: typeof ApiComplaintsRoute
    }
    '/api/auth/citizen/otp/request': {
      id: '/api/auth/citizen/otp/request'
      path: '/api/auth/citizen/otp/request'
      fullPath: '/api/auth/citizen/otp/request'
      preLoaderRoute: typeof ApiAuthCitizenOtpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/citizen/otp/verify': {
      id: '/api/auth/citizen/otp/verify'
      path: '/api/auth/citizen/otp/verify'
      fullPath: '/api/auth/citizen/otp/verify'
      preLoaderRoute: typeof ApiAuthCitizenOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutDashboardRouteChildren {
  LayoutDashboardCitizenRoute: typeof LayoutDashboardCitizenRoute
  LayoutDashboardConstituencyRoute: typeof LayoutDashboardConstituencyRoute
  LayoutDashboardDepartmentRoute: typeof LayoutDashboardDepartmentRoute
  LayoutDashboardOfficerRoute: typeof LayoutDashboardOfficerRoute
  LayoutDashboardSuperadminRoute: typeof LayoutDashboardSuperadminRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardCitizenRoute: LayoutDashboardCitizenRoute,
  LayoutDashboardConstituencyRoute: LayoutDashboardConstituencyRoute,
  LayoutDashboardDepartmentRoute: LayoutDashboardDepartmentRoute,
  LayoutDashboardOfficerRoute: LayoutDashboardOfficerRoute,
  LayoutDashboardSuperadminRoute: LayoutDashboardSuperadminRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAppointmentsRoute: typeof LayoutAppointmentsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutDevelopmentRoute: typeof LayoutDevelopmentRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutSchemesRoute: typeof LayoutSchemesRoute
  LayoutTransparencyRoute: typeof LayoutTransparencyRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutComplaintsRegisterRoute: typeof LayoutComplaintsRegisterRoute
  LayoutComplaintsTrackRoute: typeof LayoutComplaintsTrackRoute
  LayoutConsoleConstituencyRoute: typeof LayoutConsoleConstituencyRoute
  LayoutConsoleContentRoute: typeof LayoutConsoleContentRoute
  LayoutConsoleDepartmentRoute: typeof LayoutConsoleDepartmentRoute
  LayoutConsoleOfficerRoute: typeof LayoutConsoleOfficerRoute
  LayoutConsoleSuperRoute: typeof LayoutConsoleSuperRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAppointmentsRoute: LayoutAppointmentsRoute,
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutDevelopmentRoute: LayoutDevelopmentRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutSchemesRoute: LayoutSchemesRoute,
  LayoutTransparencyRoute: LayoutTransparencyRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutComplaintsRegisterRoute: LayoutComplaintsRegisterRoute,
  LayoutComplaintsTrackRoute: LayoutComplaintsTrackRoute,
  LayoutConsoleConstituencyRoute: LayoutConsoleConstituencyRoute,
  LayoutConsoleContentRoute: LayoutConsoleContentRoute,
  LayoutConsoleDepartmentRoute: LayoutConsoleDepartmentRoute,
  LayoutConsoleOfficerRoute: LayoutConsoleOfficerRoute,
  LayoutConsoleSuperRoute: LayoutConsoleSuperRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ApiComplaintsRouteChildren {
  ApiComplaintsIdRoute: typeof ApiComplaintsIdRoute
}

const ApiComplaintsRouteChildren: ApiComplaintsRouteChildren = {
  ApiComplaintsIdRoute: ApiComplaintsIdRoute,
}

const ApiComplaintsRouteWithChildren = ApiComplaintsRoute._addFileChildren(
  ApiComplaintsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiAppointmentsRoute: ApiAppointmentsRoute,
  ApiComplaintsRoute: ApiComplaintsRouteWithChildren,
  ApiDbTestRoute: ApiDbTestRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthCitizenOtpRequestRoute: ApiAuthCitizenOtpRequestRoute,
  ApiAuthCitizenOtpVerifyRoute: ApiAuthCitizenOtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
